version: '3.8'

services:
  app:
    image: ecommerce-service
    container_name: ecommerce-service
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=admin
      - DB_NAME=ecommerce
      - DB_HOST=postgres
      - DB_PORT=5432
      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
      - fullstack
    command: sh -c "/wait && /app/server"
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - DB_NAME=ecommerce
    volumes:
      - ./.database:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - fullstack
    restart: always

networks:
  fullstack:
    driver: bridge